name: khatma_ui
description: Khatma widgets
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: any
  font_awesome_flutter: 10.10.0
  time_machine: 0.9.17
  lottie: 3.3.1
  freezed_annotation: 3.1.0
  shimmer: 3.0.0
  index_generator: 4.0.1