part of 'khatma.dart';

class KhatmaBase extends Khatma {
  const KhatmaBase({
    super.id,
    super.type = KhatmaType.personal,
    required super.code,
    required super.name,
    super.description = '',
    super.unit = SplitUnit.juzz,
    required super.createDate,
    required super.startDate,
    super.endDate,
    super.theme = kDefaultKhatmaTheme,
    super.status = KhatmaStatus.active,
    super.lastUpdated,
    super.lastSync,
    super.needsSync = false,
    super.createdBy,
    super.updatedBy,
    super.repeat = false,
    super.repeats = 0,
    super.version = 1,
  });

  KhatmaBase copyWith({
    KhatmaID? id,
    KhatmaType? type,
    String? code,
    String? name,
    String? description,
    SplitUnit? unit,
    DateTime? createDate,
    DateTime? startDate,
    DateTime? endDate,
    KhatmaTheme? theme,
    KhatmaStatus? status,
    DateTime? lastUpdated,
    DateTime? lastSync,
    bool? needsSync,
    String? createdBy,
    String? updatedBy,
    bool? repeat,
    int? repeats,
    int? version,
  }) {
    return KhatmaBase(
      id: id ?? this.id,
      type: type ?? this.type,
      code: code ?? this.code,
      name: name ?? this.name,
      description: description ?? this.description,
      unit: unit ?? this.unit,
      createDate: createDate ?? this.createDate,
      startDate: startDate ?? this.startDate,
      endDate: endDate ?? this.endDate,
      theme: theme ?? this.theme,
      status: status ?? this.status,
      lastUpdated: lastUpdated ?? this.lastUpdated,
      lastSync: lastSync ?? this.lastSync,
      needsSync: needsSync ?? this.needsSync,
      createdBy: createdBy ?? this.createdBy,
      updatedBy: updatedBy ?? this.updatedBy,
      repeat: repeat ?? this.repeat,
      repeats: repeats ?? this.repeats,
      version: version ?? this.version,
    );
  }
}
