import 'package:khatma_app/src/features/khatma/domain/khatma.dart';

/// Test khatmat to be used until a data source is implemented
const kTestKhatmat = [
  Khatma(
    id: '1',
    title: 'Khatma 1',
    description: 'Description 1',
    price: 15,
    availableQuantity: 5,
    avgRating: 4.5,
    numRatings: 2,
  ),
  Khatma(
    id: '2',
    title: 'Khatma 2',
    description: 'Description 2',
    price: 13,
    availableQuantity: 5,
    avgRating: 4,
    numRatings: 2,
  ),
  Khatma(
    id: '3',
    title: 'Khatma 3',
    description: 'Description 3',
    price: 17,
    availableQuantity: 5,
    avgRating: 5,
    numRatings: 2,
  ),
  Khatma(
    id: '4',
    title: 'Khatma 4',
    description: 'Description 4',
    price: 12,
    availableQuantity: 5,
  ),
  Khatma(
    id: '5',
    title: 'Khatma 5',
    description: 'Description 5',
    price: 12,
    availableQuantity: 10,
  ),
  Khatma(
    id: '6',
    title: 'Khatma 6',
    description: 'Description 6',
    price: 12,
    availableQuantity: 10,
  ),
  Khatma(
    id: '7',
    title: 'Khatma 7',
    description: 'Description 7',
    price: 18,
    availableQuantity: 10,
  ),
  Khatma(
    id: '8',
    title: 'Khatma 8',
    description: 'Description 8',
    price: 21,
    availableQuantity: 10,
  ),
  Khatma(
    id: '9',
    title: 'Khatma 9',
    description: 'Description 9',
    price: 11,
    availableQuantity: 10,
  ),
  Khatma(
    id: '10',
    title: 'Khatma 10',
    description: 'Description 10',
    price: 11,
    availableQuantity: 10,
  ),
  Khatma(
    id: '11',
    title: 'Khatma 11',
    description: 'Description 11',
    price: 24,
    availableQuantity: 10,
  ),
  Khatma(
    id: '12',
    title: 'Khatma 12',
    description: 'Description 12',
    price: 22,
    availableQuantity: 10,
  ),
  Khatma(
    id: '13',
    title: 'Khatma 13',
    description: 'Description 13',
    price: 14,
    availableQuantity: 10,
  ),
  Khatma(
    id: '14',
    title: 'Khatma 14',
    description: 'Description 14',
    price: 16,
    availableQuantity: 10,
  ),
];
